name: black_tortoise
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  cupertino_icons: ^1.0.4
  supabase: ^0.2.14
  dotenv: ^3.0.0
  rive: ^0.8.1
  flutter_svg: ^1.0.3
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/animations/dark_bg.riv
    - lib/assets/images/dark_bg.svg

  fonts:
   - family: Montserrat
     fonts:
       - asset: lib/assets/fonts/Montserrat-Medium.ttf
         weight: 500
